-- VietCropDoctor — PostgreSQL schema
-- Automatically executed by postgres:16-alpine on first container startup
-- (mounted at /docker-entrypoint-initdb.d/init.sql in docker-compose)

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

--  Users
CREATE TABLE IF NOT EXISTS users (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    username      VARCHAR(50)  UNIQUE NOT NULL,
    email         VARCHAR(255),
    phone         VARCHAR(30),
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'farmer'
                      CHECK (role IN ('farmer', 'agronomist', 'admin')),
    is_active     BOOLEAN      NOT NULL DEFAULT true,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_username ON users (username);
CREATE INDEX IF NOT EXISTS idx_users_email    ON users (email) WHERE email IS NOT NULL;

-- Chat messages
CREATE TABLE IF NOT EXISTS chat_messages (
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id VARCHAR(64) NOT NULL,
    disease    VARCHAR(255),
    question   TEXT        NOT NULL,
    answer     TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_user_id   ON chat_messages (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_session   ON chat_messages (session_id);

-- Seed: default admin account
-- Username: admin  |  Password: Admin@1234  (change after first login)
-- Hash generated by pgcrypto crypt() — compatible with Python bcrypt.checkpw()
INSERT INTO users (username, email, password_hash, role)
VALUES (
    'admin',
    'admin@vietcropdoctor.local',
    crypt('Admin@1234', gen_salt('bf', 12)),
    'admin'
)
ON CONFLICT (username) DO NOTHING;
