apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vietcropdoctor

resources:
  - namespace.yaml
  - secret.yaml
  - ingress.yaml
  - persistentvolumeclaims.yaml

  - configmaps/configmaps.yaml
  - services/services.yaml

  - deployments/gateway.yaml
  - deployments/auth.yaml
  - deployments/vision-ai.yaml
  - deployments/rag-engine.yaml
  - deployments/orchestrator.yaml
  - deployments/analytics.yaml
