apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-config
  namespace: vietcropdoctor
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  CLICKHOUSE_HOST: "clickhouse"
  CLICKHOUSE_PORT: "8123"
  CLICKHOUSE_DB: "vietcropdoctor"
  CLICKHOUSE_USER: "admin"
  LOG_LEVEL: "INFO"
