apiVersion: v1
kind: Service
metadata:
  name: rag-engine
  namespace: vietcropdoctor
  labels:
    app: rag-engine
spec:
  type: ClusterIP
  selector:
    app: rag-engine
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      protocol: TCP
